version: '3'

services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    ports: 
    - '5432:5432'  
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  crawler:
    build:
      context: config/crawler
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - rerun-crawler-node-modules:/app/node_modules
      - ./:/app
    links:
      - postgres
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      WORKERS_COUNT: 300
      BREADS_TO_PROCESS: JE
      ENV: dev
  
volumes:
    rerun-crawler-node-modules:

